### ISSUE TITLE
AssignStyle sometimes looks bad?

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/bgracontrols#91]
When assigning the style of a TBCButton with the assign style property, sometimes gradients are horizontal instead of vertical.
Try for example mora.bcbtn, when mouse is over the blue gradient is horizontal instead of vertical.

**Comment by lainz** [comment]
More information: the preview works fine, only when assigned to the real button it happens.

**Comment by circular17** [comment]
Maybe the gradient direction is not assigned?

**Comment by lainz** [comment]
You can reproduce this bug? For example add a new BCComboBox and assign the system style with the assign style menu.

The gradient direction is set with x1, y1, x2 and y2 numbers, all looking fine for me.

**Comment by lainz** [comment]
The bug looks like this, the gradient is horizontal instead of vertical.
![screenshot1](https://user-images.githubusercontent.com/4131395/98059661-69599080-1e26-11eb-8a3c-2ca682734bb6.png)

Looking at the code everything looks fine, that's strange.

**Comment by circular17** [comment]
I confirm the bug on Linux. Strange indeed.

**Comment by lainz** [comment]
Ok, yes is very strange.

**Comment by circular17** [comment]
I think I know what the problem is. The properties have default values. In this case, it is 0 because it is not specific in the property definition. But that does not match the value after the creation of the TBCButton object.

This could solved by setting the values in the creation of the TBCGradient objet but those values are overwritten afterwards in the creation of the TBCButton object by the AssignDefaultStyle procedure.

So the default value of TBCGradient properties cannot match their value at runtime because there are various states with different initial values.

The solution I found is to set the default value to EmptySingle, which will never be used, so that the property value will always be specified in the LFM file, ensuring it has the wanted value.

Just did that on dev branch.

**Comment by lainz** [comment]
Still wrong here. I just assigned the mora.bcbtn and the gradient is still horizontal at runtime, BTW the preview of the style looks good.

**Comment by lainz** [comment]
Oh yes it's fixed. I had to delete the existing button, and then it works. I close this issue. Thanks for solving.

**Comment by circular17** [comment]
Yeah, I guess the LFM was not recompiled.
